import { AmenityCategory } from './types';

export const MOCK_DATA: AmenityCategory[] = [
  {
    id: "entertainment",
    label: "Entertainment",
    filters: [
      { label: "All", count: 8 },
      { label: "Casinos", count: 2 },
      { label: "Cinemas", count: 3 },
      { label: "Theaters", count: 3 },
    ],
    items: [
      {
        id: "e1",
        name: "Casino at Great Canadian Toronto",
        type: "Casino",
        walkTime: "25.00 mins",
        driveTime: "8.00 mins",
        distance: "3.2 km",
      },
      {
        id: "e2",
        name: "Cineplex Cinemas",
        type: "Movie Theater",
        walkTime: "18.00 mins",
        driveTime: "5.00 mins",
        distance: "2.1 km",
      },
      {
        id: "e3",
        name: "Royal Theatre",
        type: "Live Theater",
        walkTime: "22.00 mins",
        driveTime: "6.00 mins",
        distance: "2.8 km",
      },
    ],
  },
  {
    id: "shopping",
    label: "Shopping",
    filters: [
      { label: "All", count: 12 },
      { label: "Malls", count: 4 },
      { label: "Department Stores", count: 3 },
      { label: "Grocery", count: 5 },
    ],
    items: [
      {
        id: "s1",
        name: "Walmart Supercentre",
        type: "Department Store",
        walkTime: "12.00 mins",
        driveTime: "3.00 mins",
        distance: "1.5 km",
      },
      {
        id: "s2",
        name: "Yorkdale Shopping Centre",
        type: "Shopping Mall",
        walkTime: "35.00 mins",
        driveTime: "12.00 mins",
        distance: "8.5 km",
      },
      {
        id: "s3",
        name: "Metro Grocery Store",
        type: "Grocery Store",
        walkTime: "8.00 mins",
        driveTime: "2.00 mins",
        distance: "1.0 km",
      },
    ],
  },
  {
    id: "worship",
    label: "Worship",
    filters: [
      { label: "All", count: 6 },
      { label: "Churches", count: 3 },
      { label: "Temples", count: 2 },
      { label: "Mosques", count: 1 },
    ],
    items: [
      {
        id: "w1",
        name: "BAPS Shri Swaminarayan Mandir, Toronto",
        type: "Hindu Temple",
        walkTime: "15.00 mins",
        driveTime: "4.00 mins",
        distance: "2.0 km",
      },
      {
        id: "w2",
        name: "St. Mary's Catholic Church",
        type: "Catholic Church",
        walkTime: "10.00 mins",
        driveTime: "2.50 mins",
        distance: "1.2 km",
      },
      {
        id: "w3",
        name: "Toronto Central Mosque",
        type: "Mosque",
        walkTime: "20.00 mins",
        driveTime: "6.00 mins",
        distance: "3.5 km",
      },
    ],
  },
  {
    id: "sports",
    label: "Sports",
    filters: [
      { label: "All", count: 10 },
      { label: "Arenas", count: 3 },
      { label: "Gyms", count: 4 },
      { label: "Parks", count: 3 },
    ],
    items: [
      {
        id: "sp1",
        name: "Westwood Arena",
        type: "Athletic Field",
        walkTime: "8.00 mins",
        driveTime: "2.00 mins",
        distance: "1.0 km",
      },
      {
        id: "sp2",
        name: "CWENCH Centre by Canlan Sports",
        type: "Sports Complex",
        walkTime: "12.00 mins",
        driveTime: "3.00 mins",
        distance: "1.8 km",
      },
      {
        id: "sp3",
        name: "GoodLife Fitness",
        type: "Gym",
        walkTime: "6.00 mins",
        driveTime: "1.50 mins",
        distance: "0.8 km",
      },
    ],
  },
  {
    id: "food",
    label: "Food",
    filters: [
      { label: "All", count: 15 },
      { label: "Restaurants", count: 8 },
      { label: "Fast Food", count: 4 },
      { label: "Cafes", count: 3 },
    ],
    items: [
      {
        id: "f1",
        name: "Chaatter Box Restaurant Etobicoke",
        type: "Restaurant",
        walkTime: "5.00 mins",
        driveTime: "1.00 mins",
        distance: "0.5 km",
      },
      {
        id: "f2",
        name: "Tim Hortons",
        type: "Coffee Shop",
        walkTime: "3.00 mins",
        driveTime: "0.50 mins",
        distance: "0.3 km",
      },
      {
        id: "f3",
        name: "McDonald's",
        type: "Fast Food",
        walkTime: "7.00 mins",
        driveTime: "1.50 mins",
        distance: "0.9 km",
      },
    ],
  },
  {
    id: "miscellaneous",
    label: "Miscellaneous",
    filters: [
      { label: "All", count: 8 },
      { label: "Services", count: 4 },
      { label: "Utilities", count: 2 },
      { label: "Other", count: 2 },
    ],
    items: [
      {
        id: "m1",
        name: "Toronto Public Library",
        type: "Library",
        walkTime: "18.00 mins",
        driveTime: "5.00 mins",
        distance: "2.5 km",
      },
      {
        id: "m2",
        name: "RBC Bank",
        type: "Bank",
        walkTime: "10.00 mins",
        driveTime: "2.50 mins",
        distance: "1.3 km",
      },
      {
        id: "m3",
        name: "Canada Post",
        type: "Post Office",
        walkTime: "12.00 mins",
        driveTime: "3.00 mins",
        distance: "1.6 km",
      },
    ],
  },
];

