import type { PreConstructionProperty } from '../PropertyCards/types';

// Mock data for Platinum Access VIP Condos
export const platinumVIPProjects: PreConstructionProperty[] = [
  {
    id: 'vip-1',
    projectName: 'The Platinum Tower',
    developer: 'Elite Luxury Developments',
    startingPrice: 850000,
    images: [
      '/images/p1.jpg',
      '/images/p2.jpg',
      '/images/p3.jpg',
    ],
    address: {
      street: '1000 Bay Street',
      city: 'Toronto',
      province: 'Ontario',
      latitude: 43.6532,
      longitude: -79.3832,
    },
    details: {
      propertyType: 'Condominium',
      bedroomRange: '2-4',
      bathroomRange: '2-3',
      sqftRange: '1,200-2,000',
      totalUnits: 80,
      availableUnits: 12,
    },
    completion: {
      date: 'Q3 2026',
      progress: 20,
    },
    occupancyYear: 2027,
    features: ['Private Concierge', 'Rooftop Pool', 'Spa & Wellness', 'Private Wine Cellar'],
    depositStructure: '10% on signing, 5% every 6 months',
    status: 'selling',
  },
  {
    id: 'vip-2',
    projectName: 'Diamond Residences',
    developer: 'Prestige Builders',
    startingPrice: 950000,
    images: [
      '/images/p2.jpg',
      '/images/p3.jpg',
      '/images/p4.jpg',
    ],
    address: {
      street: '2000 Yonge Street',
      city: 'Toronto',
      province: 'Ontario',
      latitude: 43.7000,
      longitude: -79.4000,
    },
    details: {
      propertyType: 'Condominium',
      bedroomRange: '2-5',
      bathroomRange: '2-4',
      sqftRange: '1,500-2,500',
      totalUnits: 120,
      availableUnits: 25,
    },
    completion: {
      date: 'Q1 2027',
      progress: 15,
    },
    occupancyYear: 2027,
    features: ['Butler Service', 'Private Theater', 'Sky Garden', 'Luxury Spa'],
    depositStructure: '15% on signing, 5% every 6 months',
    status: 'selling',
  },
  {
    id: 'vip-3',
    projectName: 'Crown Heights VIP',
    developer: 'Royal Properties Group',
    startingPrice: 720000,
    images: [
      '/images/p3.jpg',
      '/images/p4.jpg',
      '/images/p5.jpg',
    ],
    address: {
      street: '1500 Bloor Street West',
      city: 'Toronto',
      province: 'Ontario',
      latitude: 43.6500,
      longitude: -79.4200,
    },
    details: {
      propertyType: 'Condominium',
      bedroomRange: '1-3',
      bathroomRange: '1-2',
      sqftRange: '800-1,500',
      totalUnits: 200,
      availableUnits: 45,
    },
    completion: {
      date: 'Q2 2026',
      progress: 30,
    },
    occupancyYear: 2026,
    features: ['VIP Lounge', 'Rooftop Terrace', 'Fitness Center', 'Concierge'],
    depositStructure: '5% on signing, 10% within 6 months',
    status: 'selling',
  },
  {
    id: 'vip-4',
    projectName: 'Exclusive Bayview Condos',
    developer: 'Summit Luxury Homes',
    startingPrice: 680000,
    images: [
      '/images/p4.jpg',
      '/images/p5.jpg',
      '/images/p6.jpg',
    ],
    address: {
      street: '3000 Bayview Avenue',
      city: 'Toronto',
      province: 'Ontario',
      latitude: 43.7500,
      longitude: -79.3800,
    },
    details: {
      propertyType: 'Condominium',
      bedroomRange: '2-4',
      bathroomRange: '2-3',
      sqftRange: '1,000-1,800',
      totalUnits: 150,
      availableUnits: 30,
    },
    completion: {
      date: 'Q4 2026',
      progress: 25,
    },
    occupancyYear: 2027,
    features: ['Private Elevator', 'Wine Storage', 'Pet Spa', 'Business Center'],
    depositStructure: '10% on signing, 5% every 6 months',
    status: 'selling',
  },
  {
    id: 'vip-5',
    projectName: 'The Signature Collection',
    developer: 'Prime Developments',
    startingPrice: 920000,
    images: [
      '/images/p5.jpg',
      '/images/p6.jpg',
      '/images/p1.jpg',
    ],
    address: {
      street: '500 King Street West',
      city: 'Toronto',
      province: 'Ontario',
      latitude: 43.6400,
      longitude: -79.3900,
    },
    details: {
      propertyType: 'Condominium',
      bedroomRange: '2-4',
      bathroomRange: '2-3',
      sqftRange: '1,300-2,200',
      totalUnits: 90,
      availableUnits: 18,
    },
    completion: {
      date: 'Q1 2027',
      progress: 18,
    },
    occupancyYear: 2027,
    features: ['Private Concierge', 'Rooftop Pool', 'Spa', 'Fine Dining'],
    depositStructure: '12% on signing, 4% every 6 months',
    status: 'selling',
  },
  {
    id: 'vip-6',
    projectName: 'Luxury Waterfront VIP',
    developer: 'Marina Developments',
    startingPrice: 1100000,
    images: [
      '/images/p6.jpg',
      '/images/p1.jpg',
      '/images/p2.jpg',
    ],
    address: {
      street: '2500 Lakeshore Boulevard',
      city: 'Toronto',
      province: 'Ontario',
      latitude: 43.6200,
      longitude: -79.4000,
    },
    details: {
      propertyType: 'Condominium',
      bedroomRange: '3-5',
      bathroomRange: '3-4',
      sqftRange: '1,800-3,000',
      totalUnits: 60,
      availableUnits: 8,
    },
    completion: {
      date: 'Q2 2027',
      progress: 12,
    },
    occupancyYear: 2028,
    features: ['Waterfront Views', 'Private Marina', 'Helipad Access', 'Butler Service'],
    depositStructure: '20% on signing, 5% every 6 months',
    status: 'selling',
  },
];

